version : '3'

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    restart: always
    container_name: mysql
    image: mysql:8.0.27
#    ports:
#      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M

  redis:
    container_name: redis
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass","123456"]
#    ports:
#      - "6379:6379"


  campus-server:
#    build:
#      context: ./
    image: registry.cn-zhangjiakou.aliyuncs.com/thymeleaf/campus-server:1.0.11
    container_name: campus-server
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8160
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: oddfar_campus
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATA: 0
      REDIS_PWD: 123456
    restart: always
    ports:
      - "8160:8160"
